[package]
name = "pngme"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
crc = "3.2.1"
nom = "7.1.3"

[lib]
name = "pngme_lib"
path = "src/lib.rs"

[[bin]]
name = "pngme"
path = "src/main.rs"
